# Generated by Django 5.0.2 on 2024-04-29 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('batch', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_achievements', models.TextField()),
                ('academic_certificate', models.FileField(upload_to='achievement_certificates/')),
                ('extracurricular_activities', models.TextField()),
                ('eca_achievements', models.FileField(upload_to='achievement_certificates/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_year', models.IntegerField()),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leetcode_profile', models.URLField()),
                ('linkedin_profile', models.URLField()),
                ('github_profile', models.URLField()),
                ('hackerrank_profile', models.URLField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
    ]
